namespace App6
{
    [default_interface]
    runtimeclass IslandPage : Microsoft.UI.Xaml.Controls.Page
    {
        IslandPage();

        Boolean  EnableSetFieldOfView;
        Single   FieldOfView;
        Boolean  FixLowFovScene;
        Boolean  DisableFog;
        Boolean  EnableSetTargetFrameRate;
        UInt32   TargetFrameRate;
        Boolean  RemoveOpenTeamProgress;
        Boolean  HideQuestBanner;
        Boolean  DisableEventCameraMove;
        Boolean  DisableShowDamageText;
        Boolean  UsingTouchScreen;
        Boolean  RedirectCombineEntry;
        Boolean  ResinListItemAllowOriginalResin;
        Boolean  ResinListItemAllowPrimogem;
        Boolean  ResinListItemAllowFragileResin;
        Boolean  ResinListItemAllowTransientResin;
        Boolean  ResinListItemAllowCondensedResin;
        Boolean  HideUid;
    }
}
