# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: masterbuild

on:
  workflow_dispatch: {}

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: .

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-2025-vs2026

    steps:
    - uses: actions/checkout@v4
      with:
        ref: refs/heads/dev   
      
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Restore NuGet packages
      working-directory: ${{ github.workspace }}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: vcpkg
      working-directory: ${{ github.workspace }}
      run: vcpkg integrate install

    - name: Build
      working-directory: ${{ github.workspace }}
      run: msbuild /m /p:Platform=x64 /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}

    - name: checkout Fulltrust
      uses: actions/checkout@v4
      with:
        repository: sigewinnefish/sigewinne-toolkit-exclusive-component
        token: ${{ secrets.pat }}
        path: sigewinne-toolkit-exclusive-component

    - name: Build Fulltrust
      working-directory: ${{ github.workspace }}/sigewinne-toolkit-exclusive-component/toolkit_fulltrust
      run: |
           cmake -DCMAKE_BUILD_TYPE=Release -D CMAKE_ASM_MASM_COMPILER="C:/Program Files/Microsoft Visual Studio/18/Enterprise/VC/Tools/MSVC/14.50.35717/bin/Hostx64/x64/ml64.exe" --preset x64-release -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake > NUL 2>&1
           cmake --build build\x64-release --target toolkit_fulltrust > NUL 2>&1

    - name: checkout Island
      uses: actions/checkout@v4
      with:
        repository: sigewinnefish/minisland
        token: ${{ secrets.pat }}
        path: minisland
  
    - name: Build Island
      working-directory: ${{ github.workspace }}/minisland
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}} > NUL 2>&1

    - name: Preparing for Packing
      working-directory: ${{ github.workspace }}
      run: |
            powershell -Command "Copy-Item './x64/Release/App6' './installer/toolkit' -Recurse -Force -Exclude '*.pdb','*.exp','*.lib','*.xbf','*.winmd'"
            powershell -Command "Copy-Item '${{ github.workspace }}\sigewinne-toolkit-exclusive-component\toolkit_fulltrust\build\x64-release\src\toolkit_fulltrust.exe' './installer/toolkit/toolkit_fulltrust.exe' -Force"
            powershell -Command "Copy-Item '${{ github.workspace }}\minisland\x64\Release\minisland.dll' './installer/toolkit/nvd3dump.dll' -Force"
            powershell -Command "Rename-Item -Path '.\installer\toolkit\App6.exe' -NewName 'toolkit.exe'"
            powershell -Command "Rename-Item -Path '.\installer\toolkit\App6.pri' -NewName 'toolkit.pri'"

    - name: Pack with kachina installer
      working-directory: ${{ github.workspace }}/installer
      run: |
            powershell -Command "Invoke-WebRequest -Uri 'https://github.com/YuehaiTeam/kachina-installer/releases/download/0.4.1/kachina-builder.exe' -OutFile './kachina-builder.exe'"
            ./kachina-builder.exe pack -t installer.png --icon installer.ico -c toolkit.config.json -o toolkit.update.exe
            ./kachina-builder.exe gen -j 8 -i toolkit -m metadata.json -r toolkit -o hashed -t 6.3b0 -u toolkit.update.exe
            ./kachina-builder.exe pack -t installer.png --icon installer.ico -c toolkit.config.json -m metadata.json -d hashed -o toolkit.Install.exe
   
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v5.0.0
      with:
        path: ${{ github.workspace }}\installer\toolkit.Install.exe

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
       tag_name: v6.4b0
       release_name: prerelease
       body: prerelease
       draft: false
       prerelease: true

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
       upload_url: ${{ steps.create_release.outputs.upload_url }}
       asset_path: ./installer/toolkit.Install.exe
       asset_name: toolkit.Install.exe
       asset_content_type: application/vnd.microsoft.portable-executable
