name: Build MSI Installer

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v6

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Install Wix Toolset 4
        run: dotnet tool install --global wix --version 4.0.1

      - name: Restore NuGet packages
        run: dotnet restore src/Snap.Hutao/Snap.Hutao.slnx

      - name: Build WinUI 3 project (self-contained)
        run: dotnet build src/Snap.Hutao/Snap.Hutao/Snap.Hutao.csproj -c Release

      - name: Build MSI installer
        run: dotnet build src/Snap.Hutao/Snap.Hutao.Installer/Snap.Hutao.Installer.wixproj -c Release

      - name: Upload MSI Artifact
        uses: actions/upload-artifact@v7
        with:
          name: Snap.Hutao-MSI
          path: |
            src/Snap.Hutao/Snap.Hutao.Installer/bin/x64/Release/en-US/*.msi
